import DropZone from "./DropZone"

const LoggedUser = ({ updateBackground }) => {
  //   console.log(deviceDetect())
  //  console.log(isMobile)

  const handleForm = (e) => {
    e.preventDefault()

    console.log("SUBMIT")
  }

  return (
    // Actual APP

    // each icon when clicked will need to change a container that will have a different link at the bottom

    // after the button is clicked under the drag and drop there should be a link generated by the API and be displayed

    <div className="app_functionality">
      <p className="select_message">
        Pick a game server you want to upload files for
      </p>

      <ul className="game_list">
        <li onClick={() => updateBackground("red")}>
          <img src="../../../../public/assets/CS16_copy.png" alt="CS 1.6" />
          <span>CS 1.6</span>
        </li>
        <li onClick={() => updateBackground("green")}>
          <img src="../../../../public/assets/CS2.webp" alt="CS 2" />
          <span>Counter Strike 2</span>
        </li>
        <li onClick={() => updateBackground("purple")}>
          <img src="../../../../public/assets/roundTF2Logo.png" alt="TF2" />
          <span>Team Fortress 2</span>
        </li>
      </ul>

      {/* container with drag and rop */}

      <form onSubmit={handleForm}>
        <h3>Upload files</h3>

        <DropZone />

        <p>
          Only the following extensions are allowed: .bsp, .vpk, .tga, mp3 and
          .wav
        </p>
      </form>

      {/* If post fetch is successful then make this div visible with the URL from the response  */}

      {/* you will need to thing about making the file handlers disappear  */}

      <div className="url_result"></div>
    </div>
  )
}
export default LoggedUser