import DropZone from "./DropZone"






const LoggedUser = () => {
  //   console.log(deviceDetect())
  //  console.log(isMobile)

  const handleForm = (e) => {
    e.preventDefault()

    console.log("SUBMIT")
  }







  return (
    // Actual APP

    // under you will have multiple icons with 4 games the icon shapes should be inspired after the games

    // each icon when clicked will need to change a container that will have a different link at the bottom

    // After the user gras some files the files will need a counter

    // they should be able to drag and drop multiple times and the files should just accumulate

    // after all the drag and drops there should be a button for upload

    // after the button is clicked under the drag and drop there should be a link generated by the API and be displayed

    <div className="app_functionality">
      {/* message */}
      <p className="select_message">
        Pick a game server you want to upload files for
      </p>

      {/* container containing the 4 games with icons and shapes */}
      <ul className="game_list">
        <li>
          <img src="../../../../public/assets/CS16.png" alt="CS 1.6" />
        </li>
        <li>
          <img src="../../../../public/assets/CS2.webp" alt="CS 2" />
        </li>
        <li>
          <img src="../../../../public/assets/TF2.jpg" alt="TF2" />
        </li>
      </ul>

      {/* container with drag and rop */}

      <form onSubmit={handleForm}>
        <h3>Upload files</h3>

        <div>
          {/* <span>Drag and drop your files</span>
          <span>file counter</span> */}

          {/* ypu might need to have around here a generated link from the API */}

          <DropZone />
        </div>

        <p>
          Only the following extensions are allowed: .bsp, .vpk, .tga, mp3 and
          .wav
        </p>
      </form>
    </div>
  )
}
export default LoggedUser