const Dashboard = () => {
  return (

    // Dashboard will need two container components

    // one will contain error and will ask user to log in

    // and one will contain the functionality of the website


    // ERROR container

    // - contains an Icon error

    // error message

    // a button for login or register


    // Actual APP

    // on top under navigation a message bar with a message : Pick a game server you want to upload filers for

    // under you will have multiple icons with 4 games the icon shapes should be inspired after the games

    // each icon when clicked will need to change a container that will have a different link at the bottom

    // there will have to be a drag and drop functionality, meaning the user should be able to drag and drop in a box their files

    // After the user gras some files the files will need a counter

    // they should be able to drag and drop multiple times and the files should just accumulate 

    // after all the drag and drops there should be a button for upload

    // after the button is clicked under the drag and drop there should be a link generated by the API and be displayed


    // QUESTION : how do I make the app recognize the login of the user?

    // is there any other way than just making a local storage variable that can be altered?


    // OPTIONAL

    // after upload button is clicked with some back and forth with the API there should be a sort of log that shows the files loading as a loading screen



    <section>
      <div className="container">
        Dashboard 

        {/* if user not logged in */}


        {/*


        
          1.Main container
          
            1.1 Will need to have two faces
              1.1.1 one for user not logged in
              1.1.2 one for logged in user 

            1.2 not logged in face
              1.2.1 will have the message: You must be logged in before uploading your own custom files
              1.2.2 will need to be either toggled on on top as a layer(You need to implement security to this one, it can be toggled off)  


        */}


      </div>
    </section>
  )
}
export default Dashboard